CreateConVar("ttt_soda_total_spawn_amount", 5, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Set the amount of sodas that spawn each round.")
CreateConVar("ttt_soda_limit_one_per_player", 0, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Limit the soda usage to one per player.")
CreateConVar("ttt_soda_speedup", 1.75, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Set the speed you can get after drinking the SpeedUp! soda. (1.5 = 150%, 1.75 = 175% etc.)")
CreateConVar("ttt_soda_rageup", 1.30, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "How much damage do you deal after drinking the RageUp! soda (1.20 = 120%, 1.40 = 140% etc.)")
CreateConVar("ttt_soda_shootup", 1.50, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "How much much shorter the delay is after ShootUp! soda (1.20 = 120%, 1.40 = 140% etc.)")
CreateConVar("ttt_soda_armorup", 10, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "How much extra armor points you receive.")
CreateConVar("ttt_soda_healup", 10, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "How much extra armor points you receive.")
CreateConVar("ttt_soda_creditup", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "How much extra equipment credits you receive.")

CreateConVar("ttt_soda_speedup_sweight", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Defines the spawn weight of this soda, 0 to disable spawn.")
CreateConVar("ttt_soda_rageup_sweight", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Defines the spawn weight of this soda, 0 to disable spawn.")
CreateConVar("ttt_soda_shootup_sweight", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Defines the spawn weight of this soda, 0 to disable spawn.")
CreateConVar("ttt_soda_jumpup_sweight", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Defines the spawn weight of this soda, 0 to disable spawn.")
CreateConVar("ttt_soda_armorup_sweight", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Defines the spawn weight of this soda, 0 to disable spawn.")
CreateConVar("ttt_soda_healup_sweight", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Defines the spawn weight of this soda, 0 to disable spawn.")
CreateConVar("ttt_soda_creditup_sweight", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE}, "Defines the spawn weight of this soda, 0 to disable spawn.")
